/*
 * File: app/view/DetailsView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sesamii.view.DetailsView', {
    extend: 'Ext.Container',
    alias: 'widget.detailsview',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Panel',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'detailsview',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                scrollable: {
                    direction: 'vertical',
                    indicators: false
                },
                layout: {
                    type: 'hbox',
                    pack: 'end'
                },
                items: [
                    {
                        xtype: 'button',
                        name: 'detailsclose',
                        text: 'Close'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'details1',
                id: 'details1',
                tpl: [
                    '<div>',
                    '    <img src="{banner}" width="100%" height="95px" />',
                    '    <img class="venue-type" src="sdk/resources/images/venue_types/barB-banner.png" />',
                    '    <div class="opening-description">',
                    '        <p class="time">Open Sun - Wed 5P - 12A, Th - Sat 9P - 2A</p><p class="description">{description}</p>',
                    '        {[getMusictype(values.music_type)]}',
                    '    </div>',
                    '</div>'
                ]
            },
            {
                xtype: 'panel',
                cls: 'details2',
                html: '<div class="left"><div class="line line0"><p>No line</p></div><div class="capacity capacity0"><p>10% Capacity</p></div></div> <div class="right"><div class="male-female"><p class="female">48%&nbsp;&nbsp;</p><p class="female">52%</p></div></div>',
                id: 'details2'
            }
        ]
    }

});