/*
 * File: app/view/ListView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sesamii.view.ListView', {
    extend: 'Ext.dataview.List',
    alias: 'widget.listview',

    requires: [
        'Ext.XTemplate',
        'Ext.Toolbar'
    ],

    config: {
        cls: 'listview',
        store: 'Liststore',
        scrollable: {
            indicators: false
        },
        itemTpl: [
            '<div class="listview-container">',
            '    <div class="image"><img src="{thumbnail}" /></div>',
            '    <div class="text">',
            '        <p class="header">{venue_name} / <span>{neighborhood}<span></p>',
            '            <p><tpl if="cover_charge">${cover_charge} cover<tpl else>No cover</tpl>&nbsp;&nbsp;|&nbsp;&nbsp;$$$$</p>',
            '                <div class="line line0"><p>No line</p></div>',
            '            <div class="capacity capacity0"><p>10% Capacity</p></div>',
            '            {[checkDeals(values.deals)]}',
            '            </div>',
            '        </div>'
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'top'
            }
        ]
    }

});