/*
 * File: app/model/ListModel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sesamii.model.ListModel', {
    extend: 'Ext.data.Model',
    alias: 'model.listmodel',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'address'
            },
            {
                name: 'avg_age'
            },
            {
                name: 'avg_female'
            },
            {
                name: 'banner'
            },
            {
                name: 'capacity'
            },
            {
                name: 'cost_rating',
                type: 'int'
            },
            {
                name: 'cover_charge'
            },
            {
                name: 'created',
                type: 'date'
            },
            {
                name: 'dancing',
                type: 'boolean'
            },
            {
                name: 'deals'
            },
            {
                name: 'description'
            },
            {
                name: 'id'
            },
            {
                name: 'latitude'
            },
            {
                name: 'line_estimate'
            },
            {
                name: 'longitude'
            },
            {
                name: 'music_tagline'
            },
            {
                name: 'music_type'
            },
            {
                name: 'neighborhood'
            },
            {
                name: 'openings'
            },
            {
                name: 'phone'
            },
            {
                name: 'thumbnail'
            },
            {
                name: 'updated'
            },
            {
                name: 'venue_name'
            },
            {
                name: 'venue_type'
            },
            {
                name: 'website'
            }
        ]
    }
});