/*
 * File: app/controller/ListController.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sesamii.controller.ListController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.listcontroller',

    config: {
        refs: {
            listview: 'listview',
            detailsview: 'detailsview',
            masterdetailsview: 'masterdetailsview',
            mainview: 'mainview',
            detailstoolbar: 'detailsview toolbar',
            detailsclose: 'button[name=detailsclose]',
            details1: 'detailsview #details1'
        },

        control: {
            "listview": {
                itemtap: 'onListItemTap'
            },
            "button[name=detailsclose]": {
                tap: 'onDetailsCloseButtonTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var mainview = this.getMainview(),
            detailsview = this.getDetailsview(),
            detailstoolbar = this.getDetailstoolbar(),
            details1 = this.getDetails1(),
            data =record.data;

        console.log(data);
        detailstoolbar.setTitle(data.venue_name);
        details1.setData(data);
        mainview.getLayout().setAnimation({
            type:'slide',
            direction:'left'
        });
        mainview.setActiveItem(detailsview);
        dataview.deselectAll();
    },

    onDetailsCloseButtonTap: function(button, e, eOpts) {
        var mainview = this.getMainview();
        mainview.getLayout().setAnimation({
            type:'slide',
            direction:'right'
        });
        mainview.setActiveItem(0);
    }

});